dist: xenial

language: cpp
cache: ccache
os: linux

jobs:
  include:
    - name: Linux/ShellCheck, Shell script lint
      os: linux
      env: IMG=cnl_ci:base-20.04 SCRIPT=test/scripts/shellcheck.sh

    - name: Linux/GCC 10, Unit test
      os: linux
      env: IMG=cnl_ci:gcc-10 SCRIPT=test/scripts/unit-test.sh STANDARD=20 GENERATOR="Unix Makefiles"

    - name: OS X/GCC 8, Unit test
      os: osx
      osx_image: xcode11.5
      env: CC=gcc-8 CXX=g++-8 PACKAGE=gcc@8 VERSION=8 SCRIPT=test/scripts/unit-test.sh STANDARD=14 INT128=OFF

    - name: OS X/Apple Clang 11, Unit test
      os: osx
      osx_image: xcode11.5
      compiler: clang
      env: CC=clang CXX=clang++ STANDARD=14 SCRIPT=test/scripts/unit-test.sh EXCEPTIONS=OFF TOOLCHAIN=clang

script:
  - .travis/test-${TRAVIS_OS_NAME}.sh
